# Generated by Django 4.2.4 on 2023-09-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=255)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=2550)),
            ],
        ),
    ]
